// Generated by CoffeeScript 1.6.3
var americano;

americano = require('americano-cozy');

module.exports = {
  alarm: {
    all: function(doc) {
      return emit(doc.title, doc);
    },
    byDate: function(doc) {
      return emit(new Date(doc.trigg), doc);
    }
  },
  event: {
    all: function(doc) {
      return emit(doc.title, doc);
    },
    byDate: function(doc) {
      return emit(new Date(doc.start), doc);
    }
  },
  user: {
    all: function(doc) {
      return emit(doc.title, doc);
    }
  },
  contact: {
    all: americano.defaultRequests.all
  },
  cozy_instance: {
    all: americano.defaultRequests.all
  }
};
