// Generated by CoffeeScript 1.6.3
var americano, tagsView;

americano = require('americano-cozy');

tagsView = {
  map: function(doc) {
    var tag, _i, _len, _ref, _results;
    _ref = doc.tags || [];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      tag = _ref[_i];
      _results.push(emit(tag, true));
    }
    return _results;
  },
  reduce: function(key, values, rereduce) {
    return true;
  }
};

module.exports = {
  alarm: {
    all: function(doc) {
      return emit(doc.title, doc);
    },
    byDate: function(doc) {
      return emit(new Date(doc.trigg), doc);
    },
    tags: tagsView
  },
  event: {
    all: function(doc) {
      return emit(doc.title, doc);
    },
    byDate: function(doc) {
      return emit(new Date(doc.start), doc);
    },
    tags: tagsView
  },
  user: {
    all: function(doc) {
      return emit(doc.title, doc);
    }
  },
  contact: {
    all: americano.defaultRequests.all
  },
  cozy_instance: {
    all: americano.defaultRequests.all
  }
};
