// Generated by CoffeeScript 1.6.3
var User, americano;

americano = require('americano-cozy');

module.exports = User = americano.getModel('User', {
  email: {
    type: String
  },
  timezone: {
    type: String,
    "default": "Europe/Paris"
  }
});

User.all = function(callback) {
  return User.request("all", callback);
};

User.destroyAll = function(callback) {
  return User.requestDestroy("all", callback);
};

User.getTimezone = function(callback) {
  return User.all(function(err, users) {
    if (err) {
      return callback(err);
    } else if (users.length === 0) {
      return callback(new Error('no user'));
    } else {
      return callback(null, users[0].timezone);
    }
  });
};

User.updateTimezone = function(callback) {
  return User.getTimezone(function(err, timezone) {
    if (err) {
      console.log(err);
      User.timezone = "Europe/Paris";
    } else {
      User.timezone = timezone || "Europe/Paris";
    }
    return typeof callback === "function" ? callback() : void 0;
  });
};
