// Generated by CoffeeScript 1.6.3
var Event, MailHandler, User, VCalendar, mails, time;

time = require('time');

User = require('../models/user');

Event = require('../models/event');

VCalendar = require('cozy-ical').VCalendar;

MailHandler = require('../mails/mail_handler');

mails = new MailHandler();

module.exports.fetch = function(req, res, next, id) {
  var _this = this;
  return Event.find(id, function(err, event) {
    if (err || !event) {
      return res.send({
        error: "Event not found"
      }, 404);
    } else {
      req.event = event;
      return next();
    }
  });
};

module.exports.all = function(req, res) {
  return Event.all(function(err, events) {
    var evt, index, _i, _len;
    if (err) {
      return res.send({
        error: 'Server error occurred while retrieving data'
      });
    } else {
      for (index = _i = 0, _len = events.length; _i < _len; index = ++_i) {
        evt = events[index];
        events[index] = evt.timezoned();
      }
      return res.send(events);
    }
  });
};

module.exports.read = function(req, res) {
  return res.send(req.event.timezoned());
};

module.exports.create = function(req, res) {
  var data,
    _this = this;
  data = Event.toUTC(req.body);
  return Event.create(data, function(err, event) {
    if (err) {
      return res.error("Server error while creating event.");
    }
    return res.send(event.timezoned(), 201);
  });
};

module.exports.update = function(req, res) {
  var data,
    _this = this;
  data = Event.toUTC(req.body);
  return req.event.updateAttributes(data, function(err, event) {
    if (err != null) {
      return res.send({
        error: "Server error while saving event"
      }, 500);
    } else {
      return mails.sendInvitations(event, function(err, event2) {
        if (err) {
          console.log(err);
        }
        return res.send((event2 || event).timezoned(), 200);
      });
    }
  });
};

module.exports["delete"] = function(req, res) {
  return req.event.destroy(function(err) {
    if (err != null) {
      return res.send({
        error: "Server error while deleting the event"
      }, 500);
    } else {
      return mails.sendDeleteNotification(req.event, function() {
        return res.send({
          success: true
        }, 200);
      });
    }
  });
};

module.exports["public"] = function(req, res) {
  var key, visitor, _ref,
    _this = this;
  key = req.query.key;
  if (!(visitor = req.event.getGuest(key))) {
    return res.send({
      error: 'invalid key'
    }, 401);
  }
  if ((_ref = req.query.status) === 'ACCEPTED' || _ref === 'DECLINED') {
    return visitor.setStatus(req.query.status, function(err) {
      if (err) {
        return res.send({
          error: "server error occured"
        }, 500);
      }
      res.header({
        'Location': "./event" + req.event.id + "?key=" + key
      });
      return res.send(303);
    });
  } else {
    return res.render('event_public.jade', {
      event: req.event.timezoned(),
      key: key,
      visitor: visitor
    });
  }
};

module.exports.publicIcal = function(req, res) {
  var calendar, key, visitor;
  key = req.query.key;
  if (!(visitor = req.event.getGuest(key))) {
    return res.send({
      error: 'invalid key'
    }, 401);
  }
  calendar = new VCalendar('Cozy Cloud', 'Cozy Agenda');
  calendar.add(req.event.toIcal());
  res.header({
    'Content-Type': 'text/calendar'
  });
  return res.send(calendar.toString());
};
